# Introduction to `numpy`

This Notebook provides an overview of the capabilities of the `numpy` module. It covers Sect. II of [Modules_in__python.ipynb](Modules_in__python.ipynb). 

## Table of Content

- [II. Numpy](#II)
    * [II.1 Array Definition and construction](#II.1)
    * [II.2 Array copies and views](#II.2)
    * [II.3 Shape manipulation](#II.3)
    * [II.4 What makes numpy Arrays useful structures ?](#II.4)
        - [II.4.1 ufunc](#II.4.1)
        - [II.4.2 Aggregation](#II.4.2)
        - [II.4.3 Broadcasting](II.4.3)
        - [II.4.4 Slicing, masking, fancy indexing](#II.4.4)
    * [II.5 Reading arrays from a file and string formatting](#II.5)
    * [II.6 Useful Numpy functions](#II.6)
    * [II.7 Summary](#II.7)
    * [II.8 References](#VI)

## II. `numpy`:  <a class="anchor" id="II"></a>

`numpy` can be seen as the implementation of mathematical functions and operations for python language. One can have an array of the dimension he wants. It also introduces one key object `arrays`. 

### II.1 `array` definition and construction:  <a class="anchor" id="II.1"></a>

- A `numpy` array is an object of the type `np.ndarray` (although this type specifier is rarely used directly). Instead one can create arrays in several ways: 

``` python
import numpy as np
np.array([1,2,3,4])   # creates an array from a python list
np.array([[0, 1, 2], [3, 4, 5]])   # Creates a 2D array from a python list
np.empty(shape=(2,3)) # Creates an "empty" (entry not initialised) array with 2 rows and 3 columns 
np.arange(5) # similar to the built-in range() function.
np.linspace(1, 10, 10) # creates an array of 10 elements from 1 to 10
np.zeros(10)  # creates an array of 10 elements filled with 0
np.ones(10)   # creates an array of 5 elements filled with 1
np.zeros((2, 5))  # mulitdimensional arrays of 2 rows and 5 columns

```
- 2-D arrays of `shape=(r, c)` are arrays with `r` *rows* and `c` *columns*. 

In [3]:
# Let's try the above commands and visualise the output. 
# Here is an array which is a list containing here lists as elements
# Watch out the double [[]] in the definition of the array. Without it, the function shape can returns us errors. 
import numpy as np
a = np.array([[1,2,3], [3,5,5]])
a

array([[1, 2, 3],
       [3, 5, 5]])

In [111]:
# Gives the number of rows first and then the number of columns
np.shape(a)

(5,)

In [7]:
# We can already create the shape of the array without filling it
empty_array = np.empty(shape=(2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# It is better to use .zeros because .empty can sometimes put very small values instead of zeros
# By default, the .zeros array would say that the array is filled with float
zero_array = np.zeros(shape=(2,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [112]:
ones_array = np.ones(shape=(2,2,3))
ones_array  # [1,1,0]

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
# We won't get the type of the elements that way
type(zero_array)

numpy.ndarray

In [11]:
# dtype gives the type of the elements included in the array
zero_array.dtype

dtype('float64')

In [113]:
# Here note that the type of the value, which is string, has to be specified
array_of_string = np.array(['qqqq', 'a', 'f'], dtype=str)
array_of_string

array(['qqqq', 'a', 'f'], dtype='<U4')

In [121]:
# This king of array can also be created without filling it
# I have to put '<U6' for dtype to be able to put string with maximum 6 letters
another_array_of_string = np.zeros(shape=(3), dtype='<U6')

In [120]:
my_string = 'hello'
another_array_of_string[1] = my_string
another_array_of_string

array(['', 'hello', ''], dtype='<U6')

In [18]:
for i in range(5):
    print(i)

0
1
2
3
4


In [25]:
# The elements are between 0 and 5 by 0.5 steps
# The inferior born is included but not the upper born
np.arange(0., 5., 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [26]:
# Here we ask an array which elements are beteween 0 and 5 included and we ask to have 9 elements
np.linspace(0, 5, 9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

- numpy has also tools to create arrays filled with random elements:

``` python
np.random.random(size=4)  # uniform between 0 and 1
np.random.normal(size=4)  # elements are std-normal distributed so from a gaussian distribution centered on 0 
                          # with sigma=1 so we can have negative numbers

```

In [ ]:
# Try out the above commands

- You can explicitly specify which **data-type** you want:

``` python 
c = np.array([1, 2, 3], dtype=float)
c.dtype
    Out: dtype('float64')
```

In [ ]:
# Try out the above commands 

The default data type is floating point. Other possible data types are: 

* **COMPLEX** numbers: 
``` python
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype
    Out: dtype('complex128')
```

In [ ]:
# Try out the above commands 

* **BOOL**:
``` python
e = np.array([True, False, False, True])
e.dtype
    Out: dtype('bool')
```

In [ ]:
# Try out the above commands 

* **String**:
``` python
f = np.array(['abc', 'eddafg', 'hjk'])
f.dtype
    Out: dtype('S6')   # <--- String of 6 characters (by default largest elements of the array 
```

In [ ]:
# Try out the above commands 

* **Other data types**:  `int32`, `int64`, `uint32`, `uint64`  (uint = unsigned integer => only positive integers)

Note that `type(f)` tells you that `f` is a numpy array, while `f.dtype` gives you the *type of the elements* containted in `f`. `dtype` is an attribute of the object `np.array`. If you try to access the attribute dtype of a List, you will get an error message. 

In [28]:
# Difference between type/dtype; application to List/arrays.
# dtype can also be used with arrays and not with lists
f = np.array(['abc', 'eddafg', 'hjk'])
print(type(f))
print(f.dtype)
print('----------')
L = ['abc', 'eddafg', 'hjk']
print(type(L))
print(L.dtype)

<class 'numpy.ndarray'>
<U6
----------
<class 'list'>


AttributeError: 'list' object has no attribute 'dtype'

- Last but not least, `numpy` is also the package that allows you to calculate many common mathematical function (see also [`ufunc`](#II.4.1)): `np.log10()` (base 10 log), `np.log()` (natural log), `np.exp()`, `np.sin()`, `np.cos()`, etc. See the list of `numpy` mathematical functions [here](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [29]:
# create an array of floats and calculate its log / sin / ... 
#x = np.linspace(-2*np.pi, 2*np.pi, 20.)
np.log(2.3)

0.8329091229351039

In [31]:
# The constant pi is already defined in np
np.pi

3.141592653589793

In [33]:
theta = np.linspace(-2 * np.pi, 2 * np.pi, 10)
print (theta)

[-6.28318531 -4.88692191 -3.4906585  -2.0943951  -0.6981317   0.6981317
  2.0943951   3.4906585   4.88692191  6.28318531]


In [122]:
# When we apply a function to an array it apply it to all the elements
# The functions sin, cos,... ar by default giving results in radians
np.sin(theta)

array([ 2.44929360e-16,  9.84807753e-01,  3.42020143e-01, -8.66025404e-01,
       -6.42787610e-01,  6.42787610e-01,  8.66025404e-01, -3.42020143e-01,
       -9.84807753e-01, -2.44929360e-16])

In [35]:
# There are a lot of functions that are already defined in np
np.deg2rad(90)

1.5707963267948966

In [36]:
theta.shape

(10,)

In [37]:
# We can do a slicing like for the list
theta[3:6]

array([-2.0943951, -0.6981317,  0.6981317])

**Exercise:**   
For the array:
``` python
a = np.array([[1,2,3,4], [4,5,6,7], [2,3,4,5] ])
```
- What is the output of `a.ndim`, `a.shape`, `len(a)` ?     
- How does the above commands relate to the rows, columns, dimensions ?       
- How do you access 2nd item of the first row ?   

*Note:* 
Try to do the same with the following array:
``` python
b = np.array([[1,2,3], []])
```

In [66]:
# The function len(a) gives us the number of elements contained in the array
# The function .shape gives us the structure of the array so the number of rows and columns
# The function .ndim gives the dimensions/number of axis in the array 
a = np.array([[1,2,3,4], [4,5,6,7], [2,3,4,5] ])
print(a.ndim)
print(a.shape)
print(len(a))

# With .shape we see that there is 3 rows and 4 colums so to display the second element of the first row we do

a[0,1]

# Note that we have to count beginnig at 0

2
(3, 4)
3


2

**Exercise:** Elementwise operations

In the code cell below, try simple arithmetic elementwise operations: 
- add even elements with odd elements using 2 different techniques (slicing and list comprehension)
- Time the two solution using %timeit.
- Generate an array from a list made of strings and floats. What is the final array type ?
- Generate 2 arrays such that their elements are as follow :    
   `[2^0, 2^1, 2^2, 2^3, 2^4]`    
   `a_i = 2^(3*i) - i `    
   
Expected output: 
``` python
[1 2 4 8 16]    
[  1   7  62 509]    
```

In [69]:
L = [3.45, 'hello', 8.12]
a = np.array([L])
print(a.dtype)

<U32


In [126]:
b = np.array([2**i for i in np.arange(5)])
print(b)

[ 1  2  4  8 16]


In [85]:
# Another way to do it is
a1 = np.ones(5)*2
b1 = np.arange(5)
c = a1**b1
c

array([ 1.,  2.,  4.,  8., 16.])

In [80]:
c = np.array([2**(3 * i) - i for i in np.arange(10)])
print(c)


[        1         7        62       509      4092     32763    262138
   2097145  16777208 134217719]


In [86]:
d = np.arange(10)
print('even + odd elements:', d[0::2] + d[1::2])
print('even numbers are:', d[0::2])
print('and the odd elements are:', d[1::2])


even + odd elements: [ 1  5  9 13 17]
even numbers are: [0 2 4 6 8]
and the odd elements are: [1 3 5 7 9]


In [87]:
[d[2*i] + d[2*i+1] for i in range(5)]

[1, 5, 9, 13, 17]

In [136]:
# Timeit to see which solution is better/faster
d = np.arange(10)
%timeit [d[2*i] + d[2*i+1] for i in range(5)]
d

4.75 µs ± 251 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### II.2 `array` copies and views:   <a class="anchor" id="II.2"></a>

A slicing operation creates a **view** on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. More information about copies and views can be found in [Modules_in_python_numpy_adv.ipynb](Modules_in_python_numpy_adv.ipynb), but can be ignored if this is your first contact with `numpy`. 

### II.3 Array shape manipulation <a class="anchor" id="II.3"></a>

There are various possibilities to modify arrays (e.g. adding a row/column, shuffle columns, flatten, resize,...). They are discussed in details in [Modules_in_python_numpy_adv.ipynb](Modules_in_python_numpy_adv.ipynb). Let's focus here on array reshaping (which allows to perform several of the operations outlined above). 

- **II.3.1 Reshaping**:   
The method `reshape(newshape)` allows one to reorganise the elements of an array, to create a "new" array (see below) that has a different shape. The total number of items of the array has to be the same ! This method can also be used to add an axis or to flatten an array. 

In [90]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a, a.shape) 
b = a.reshape((3, 2))
b

[[1 2 3]
 [4 5 6]] (2, 3)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
# Alternatively when we know that we want 2 rows for exemple, as the number of elements is fixed, specifying the number of
# columns in the reshape is not mandatory
a.reshape((3, -1))    # unspecified (-1) value is inferred

array([[1, 2],
       [3, 4],
       [5, 6]])

### II.4 What makes `numpy` arrays useful structures ?  <a class="anchor" id="II.4"></a>

Python is fast *for coding and developping* but python is slow when it comes to *execution*, especially when it comes to execution of `for` loops.    
The reason behind this low speed is e.g. that when it does `for a in range(10): a + b`, it has to check the `type` of `a`, of `b` and of *each value* in those lists before executing. 

`numpy` helps speeding up code through 4 strategies:
1. `ufunc`
2. aggregation
3. broadcasting
4. slicing, masking, fancy indexing

#### II.4.1 `ufunc`: operates elementwise on objects. <a class="anchor" id="II.4.1"></a>

Those `ufunc` (universal functions) are included (compiled) in `numpy` and consist of fast elementwise operations. They include: 

- all mathematic operation: +, -, /, *, `***` 
- Mathematical expressions: sin, exp, cos, log10, ... 
- Comparison operators <, >, =, ...
- etc ... 

**Example:**
``` python
import numpy as np
# Basic python
a = [1,2,3,4,5]
b = [ val + 5 for val in a]   # add 5 to each element of the list  
# In numpy
a = np.array(a)
b = a + 5                     # add 5 to each element of the array.
```

In [93]:
a = [1,2,3,4,5]
b = [ val + 5 for val in a]   # add 5 to each element of the list
b

[6, 7, 8, 9, 10]

In [94]:
a = np.array(a)
b = a + 5   
b

array([ 6,  7,  8,  9, 10])

In [99]:
# implement the above example for a list of 1000 elements 
# use %timeit before calculating b to see improvement in speed
a_a = np.arange(1000)
%timeit a_a+5

3.96 µs ± 242 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [98]:
a_l = range(1000)
%timeit [val + 5 for val in a_l]

160 µs ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### II.4.2 *aggregation*:   <a class="anchor" id="II.4.2"></a>

Functions which summarize values of an array such as `min`, `max`, `sum`, `mean`, ... 

**Example:**

``` python
# python version of an aggregation
from random import random
c = [ random() for i in range(10000) ]
%timeit min(c)
#same in numpy:
c = np.array(c)
%timeit c.min()  
```
This also works on multidimensional arrays: 

``` python 
M = np.random.randint(0, 10, (10,4))
M.sum(axis=0)
M.sum(axis=1)
```

Aggregation available: 
`np.min()`, `np.max`, `np.prod()`, `np.mean()`, `np.std()`, `np.median()`, `np.any()`, `np.all()`, `np.nanmin()` (and nan versions of above aggregation), `np.argmin()`, `np.argmax()`, `np.percentile()`, ...


In [100]:
from random import random
c = [ random() for i in range(10000) ]
%timeit min(c)

276 µs ± 65.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [101]:
c = np.array(c)
%timeit c.min()

14 µs ± 1 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### II.4.3 *Broadcasting*:   <a class="anchor" id="II.4.3"></a>

Set of rules by which `ufuncs` operates on arrays of different sizes and/or dimensions. 

The term [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) describes how `numpy` treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.
Application to three cases: 

![From astroML book](../Figures/fig_broadcast_visual_1.png)



The rules / how this works:

* If array shapes differ, left-pad the smaller shape with 1s 
* If any dimension does not match, broadcast the dimension with size 1
* If neither non matching dimensions is 1 raise an error

This broadcasting strategy allows one to avoid doing `for` loops for some operations. 


#### II.4.4 Slicing, masking and fancy indexing:    <a class="anchor" id="II.4.4"></a>
	 
- **Mask**: a mask is a boolean array that can be used to "mask" some indices of an array: 

``` python
mask = np.array([False, False, True, False, True, False])
c = np.array([1, 3, 6, 9, 10, 2])
c[mask]
    Out: array([6, 10])
    
mask = (c < 4) | (c > 8)
c[mask]
    Out: array([1, 3, 9, 10, 2])
```
 

In [104]:
# The mask considers the elements which correpond to a true and skips those which correspond to a false
mask = np.array([False, False, True, False, True, False])
print(mask)
c = np.array([1, 3, 6, 9, 10, 2])
c[mask]

[False False  True False  True False]


array([ 6, 10])

In [106]:
# We can select elements by characteristics (here smaller than 4 and bigger than 8)
mask = (c < 4) | (c > 8)
c[mask]

array([ 1,  3,  9, 10,  2])

- **Fancy indexing**: passing a list/array of indices to get elements of a numpy array  (this only works for arrays !) This avoids to loop over the indices. 

``` python
ind = [1, 3, 4]
c[ind]  
   Out: array([3, 9, 10])
```

In [105]:
# We chose the elements we display by a list of indexes
ind = [1, 3, 4]
c[ind]

array([ 3,  9, 10])

In [108]:
# We can also display a selection of elements by displaying the corresponding mask
greater_than_9 = c > 9
greater_than_9

array([False, False, False, False,  True, False])

In [110]:
# We can just do
c[c>9]

array([10])

- **Multi-dimensional** array: 

We can apply mask and fancy indexing in multidimension.   
Remember that first index is row, and second is column.   
Remember how slicing works: `a[start:end:step]`   : 
- Omitting one value goes up to the end of the sequence. 
- Omitting the second "colon" implies step=1.  
- With negative steps you count backward
- Start/step can be either positive or negative indices (but then you count from the end). 

In [137]:
a = np.arange(10)
print(a)
a[a>3]

[0 1 2 3 4 5 6 7 8 9]


array([4, 5, 6, 7, 8, 9])

``` python
M = np.arange(12).reshape((3,4))
    Out: 
    array([[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]])

M[0,1] # gives value at row 0 and column 1. 
M[:, 1]  # Combines slices and indices -> all rows of column one
M[M-3 < 2]# can also do masking of n dimensional array
M[[1,0], :2] # Use fancy indexing and slicing - 1st 2 elements, of rows 1 and 2
M[M.sum(axis=1) > 2, 4:] # mixing masking and slicing 
```

An illustration of indexing in numpy arrays:
![Illustration of `np` indexing](../Figures/numpy_indexing.png)

**Exercise**:
- Try the different flavours of slicing, using start, end and step: starting from a linspace, try to obtain odd numbers counting backwards, and even numbers counting forwards. Expected Output: `[9 7 5 3 1]` and `[ 0  2  4  6  8 10]` 

- Reproduce the slices in the diagram above. You may use the following expression to create the array:    
`np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]`

In [189]:
aa = np.linspace(0, 10, 11, dtype=int)
print(aa)
# odd numbers counting backwards
print(aa[9::-2])
# Even numbers counting forward
print(aa[0::2])

[ 0  1  2  3  4  5  6  7  8  9 10]
[9 7 5 3 1]
[ 0  2  4  6  8 10]


In [190]:
# Implement the exercise above
a_tot = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]
a_tot

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [195]:
# Gives us the element that are in the row 0 and in the column 4 and 5 because the element [0,5] is excluded
# so it gives us the elements [0,3] and [0,4]
a_tot[0,3:5]

array([3, 4])

In [196]:
# Gives all elements with row >= 4 and column >=4
a_tot[4:,4:]

array([[44, 45],
       [54, 55]])

In [197]:
# Gives all the elements in the column 2
a_tot[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [198]:
# Gives the elements of pair rows beginning at 2 and of par column
a_tot[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

### II.5 Reading arrays from a file and string formatting:    <a class="anchor" id="II.5"></a>

There are now multiple modules existing to manipulate data saved in files (text files or many others). Often, we simply want/have to read a table and do operations on it. This can be done easily within `numpy`: there is a simple pair of commands to read/write a 2D array into a text file: reading tables saved in a formated text file can be done with `numpy.loadtxt('myfile.txt')`, while saving your array is done with `numpy.savetxt('myfile.txt')`.   

In [4]:
# It is to load text files, in return we have written characters
data = np.loadtxt('data.txt')

In [24]:
# It saves the data in a text file
np.savetxt('data_new.txt', data)

In [4]:
# To see the data as we are in a text editor
!more data.txt

# Name ID RA DEC z z_err zQF 
0011 11.0 69.60398 -12.33483 0.14502699731 5.39539923983e-05 0.0 
0038 38.0 69.5969 -12.32047 0.502938602945 0.000222303791245 1.0 
0042 42.0 69.57136 -12.31795 0.0 0.001 0.0 
0055 55.0 69.59832 -12.31157 0.0 0.001 0.0 
0057 57.0 69.5978429 -12.311442 0.0 0.001 0.0 
0072 72.0 69.61111 -12.3037 0.0 0.001 0.0
0080 80.0 69.55023 -12.30339 0.0 0.001 0.0
0083 83.0 69.58752 -12.30232 0.0 0.001 0.0
0085 85.0 69.56567 -12.30147 0.0 0.001 0.0
0111 111.0 69.59927 -12.29414 0.0 0.001 0.0
0114 114.0 69.52129 -12.2893 0.0 0.001 0.0
0119 119.0 69.5651 -12.28924 0.0 0.001 0.0
0125 125.0 69.53808 -12.28883 0.0 0.001 0.0
0126 126.0 69.54177 -12.28782 0.0 0.001 0.0
0128 128.0 69.60646 -12.28668 0.369864207858 8.03355766875e-05 0.0
0164 164.0 69.52007 -12.24671 0.581369862213 0.000216496440347 2.0
0182 182.0 69.53533 -12.25025 0.0 0.001 0.0
0185 185.0 69.52459 -12.24947 0.585115787002 0.000104162060008 0.0
0190 190.0 69.55228 -12.25292 0.0 0.001 0.0


In [7]:
# We can also print it as an array
data

array([[ 1.10000000e+01,  1.10000000e+01,  6.96039800e+01,
        -1.23348300e+01,  1.45026997e-01,  5.39539924e-05,
         0.00000000e+00],
       [ 3.80000000e+01,  3.80000000e+01,  6.95969000e+01,
        -1.23204700e+01,  5.02938603e-01,  2.22303791e-04,
         1.00000000e+00],
       [ 4.20000000e+01,  4.20000000e+01,  6.95713600e+01,
        -1.23179500e+01,  0.00000000e+00,  1.00000000e-03,
         0.00000000e+00],
       [ 5.50000000e+01,  5.50000000e+01,  6.95983200e+01,
        -1.23115700e+01,  0.00000000e+00,  1.00000000e-03,
         0.00000000e+00],
       [ 5.70000000e+01,  5.70000000e+01,  6.95978429e+01,
        -1.23114420e+01,  0.00000000e+00,  1.00000000e-03,
         0.00000000e+00],
       [ 7.20000000e+01,  7.20000000e+01,  6.96111100e+01,
        -1.23037000e+01,  0.00000000e+00,  1.00000000e-03,
         0.00000000e+00],
       [ 8.00000000e+01,  8.00000000e+01,  6.95502300e+01,
        -1.23033900e+01,  0.00000000e+00,  1.00000000e-03,
         0.0000000

#### II.5.1 What if my input/output file is not just a simple array ? 

More advanced functions exist in `numpy` to read text/csv files, accounting fro missing values, excluding columns, guess data type ... See [Modules_in_python_numpy_adv.ipynb](Modules_in_python_numpy_adv.ipynb) to learn about them. 

To deal with more advanced table formating, I strongly encourage you to look at the following two modules that generate specific objects with a bit more capabilities than arrays: 

- `Table` and `QTable` (table that manipulates quantities) objects in `astropy.table` and : https://docs.astropy.org/en/stable/table/ . `Table` objects may be sufficient for most of your needs and manages many different formats (including csv, latex, rdb, hdf5, ...). Conversion to/from numpy arrays and to/from `pandas.DataFrame` is often possible. Within Jupyter Notebooks, Tables are also "pretty printed", which eases analysis. 

- `DataFrame` and `Series` objects in `pandas`: https://pandas.pydata.org/pandas-docs/stable/getting_started/overview.html. Those objects/structures are commonly used in data science and machine learning. They manage an even larger variety of input files than `astropy.table` (e.g. excel and sql tables, pickle objects, ...) but Dataframe, being more versatile that astropy Tables, can also be trickier to manipulate. 

In [9]:
# It is an example of the functions we can have in astropy.table
# We can also do the slicing
# This is a bit beyond the scope of the course, this is just for information but the here documentation if we want
from astropy.table import Table
Tdata = Table.read('data.txt', format = 'ascii')
Tdata

<Table length=19>
 Name    ID       RA        DEC           z              z_err         zQF  
int32 float64  float64    float64      float64          float64      float64
----- ------- ---------- ---------- -------------- ----------------- -------
   11    11.0   69.60398  -12.33483  0.14502699731 5.39539923983e-05     0.0
   38    38.0    69.5969  -12.32047 0.502938602945 0.000222303791245     1.0
   42    42.0   69.57136  -12.31795            0.0             0.001     0.0
   55    55.0   69.59832  -12.31157            0.0             0.001     0.0
   57    57.0 69.5978429 -12.311442            0.0             0.001     0.0
   72    72.0   69.61111   -12.3037            0.0             0.001     0.0
   80    80.0   69.55023  -12.30339            0.0             0.001     0.0
   83    83.0   69.58752  -12.30232            0.0             0.001     0.0
   85    85.0   69.56567  -12.30147            0.0             0.001     0.0
  111   111.0   69.59927  -12.29414            0.0             0.001     0.0
  114   114.0   69.52129   -12.2893            0.0             0.001     0.0
  119   119.0    69.5651  -12.28924            0.0             0.001     0.0
  125   125.0   69.53808  -12.28883            0.0             0.001     0.0
  126   126.0   69.54177  -12.28782            0.0             0.001     0.0
  128   128.0   69.60646  -12.28668 0.369864207858 8.03355766875e-05     0.0
  164   164.0   69.52007  -12.24671 0.581369862213 0.000216496440347     2.0
  182   182.0   69.53533  -12.25025            0.0             0.001     0.0
  185   185.0   69.52459  -12.24947 0.585115787002 0.000104162060008     0.0
  190   190.0   69.55228  -12.25292            0.0             0.001     0.0

#### II.5.2. What if my input file mixes columns and normal rows ?

The lower-level manipulation of a text file is through the used of the `file()` object. 
For this, three operations are generally needed: 

``` python
with open('myfile.txt', 'r') as f: # 'r' for read mode, 'w' for write mode, 'a' for append mode)
    read_data = f.read() # this would read the whole file as a single string ; other methods allow one more flexible read

# One can also do the following (see below) but there is the risk to get the file not being properly closed if we forget to use the .close() function or if we still use the elements of the file. 
f = open('myfile.txt', 'r')  
f.read()  
f.close() 
```

If you do `f.read()` twice, you will see an empty string ... as the object instance then "points" to the end of the file, and there is nothing left to read. Somehow, the methods that access the file object go sequentially through the "string content" of that object. With `read()` you take the string as a whole (which could be a problem memory-wise if the file is large !). 


In [11]:
with open('data.txt', 'r') as f: 
    read_data = f.read() 

In [14]:
# It will be a SINGLE string
# The character \n means that we are going to an other line in the file 
read_data

'# Name ID RA DEC z z_err zQF \n0011 11.0 69.60398 -12.33483 0.14502699731 5.39539923983e-05 0.0 \n0038 38.0 69.5969 -12.32047 0.502938602945 0.000222303791245 1.0 \n0042 42.0 69.57136 -12.31795 0.0 0.001 0.0 \n0055 55.0 69.59832 -12.31157 0.0 0.001 0.0 \n0057 57.0 69.5978429 -12.311442 0.0 0.001 0.0 \n0072 72.0 69.61111 -12.3037 0.0 0.001 0.0\n0080 80.0 69.55023 -12.30339 0.0 0.001 0.0\n0083 83.0 69.58752 -12.30232 0.0 0.001 0.0\n0085 85.0 69.56567 -12.30147 0.0 0.001 0.0\n0111 111.0 69.59927 -12.29414 0.0 0.001 0.0\n0114 114.0 69.52129 -12.2893 0.0 0.001 0.0\n0119 119.0 69.5651 -12.28924 0.0 0.001 0.0\n0125 125.0 69.53808 -12.28883 0.0 0.001 0.0\n0126 126.0 69.54177 -12.28782 0.0 0.001 0.0\n0128 128.0 69.60646 -12.28668 0.369864207858 8.03355766875e-05 0.0\n0164 164.0 69.52007 -12.24671 0.581369862213 0.000216496440347 2.0\n0182 182.0 69.53533 -12.25025 0.0 0.001 0.0\n0185 185.0 69.52459 -12.24947 0.585115787002 0.000104162060008 0.0\n0190 190.0 69.55228 -12.25292 0.0 0.001 0.0\n'

The function `readlines()` reads in the whole file and splits it into a **list** of lines. 
``` python
f = open('myfile.txt', 'r')
for line in f.readlines():
    print(repr(line))
```

In [16]:
# We end with lists of strings
f = open('data.txt', 'r')
a = f.readlines()
a

['# Name ID RA DEC z z_err zQF \n',
 '0011 11.0 69.60398 -12.33483 0.14502699731 5.39539923983e-05 0.0 \n',
 '0038 38.0 69.5969 -12.32047 0.502938602945 0.000222303791245 1.0 \n',
 '0042 42.0 69.57136 -12.31795 0.0 0.001 0.0 \n',
 '0055 55.0 69.59832 -12.31157 0.0 0.001 0.0 \n',
 '0057 57.0 69.5978429 -12.311442 0.0 0.001 0.0 \n',
 '0072 72.0 69.61111 -12.3037 0.0 0.001 0.0\n',
 '0080 80.0 69.55023 -12.30339 0.0 0.001 0.0\n',
 '0083 83.0 69.58752 -12.30232 0.0 0.001 0.0\n',
 '0085 85.0 69.56567 -12.30147 0.0 0.001 0.0\n',
 '0111 111.0 69.59927 -12.29414 0.0 0.001 0.0\n',
 '0114 114.0 69.52129 -12.2893 0.0 0.001 0.0\n',
 '0119 119.0 69.5651 -12.28924 0.0 0.001 0.0\n',
 '0125 125.0 69.53808 -12.28883 0.0 0.001 0.0\n',
 '0126 126.0 69.54177 -12.28782 0.0 0.001 0.0\n',
 '0128 128.0 69.60646 -12.28668 0.369864207858 8.03355766875e-05 0.0\n',
 '0164 164.0 69.52007 -12.24671 0.581369862213 0.000216496440347 2.0\n',
 '0182 182.0 69.53533 -12.25025 0.0 0.001 0.0\n',
 '0185 185.0 69.52459 -12.24

In [17]:
a[10].replace('.', ',')

'0111 111,0 69,59927 -12,29414 0,0 0,001 0,0\n'

In [19]:
# It is not remove in the full file, it was just a view/copy of a specific part of the list
a

['# Name ID RA DEC z z_err zQF \n',
 '0011 11.0 69.60398 -12.33483 0.14502699731 5.39539923983e-05 0.0 \n',
 '0038 38.0 69.5969 -12.32047 0.502938602945 0.000222303791245 1.0 \n',
 '0042 42.0 69.57136 -12.31795 0.0 0.001 0.0 \n',
 '0055 55.0 69.59832 -12.31157 0.0 0.001 0.0 \n',
 '0057 57.0 69.5978429 -12.311442 0.0 0.001 0.0 \n',
 '0072 72.0 69.61111 -12.3037 0.0 0.001 0.0\n',
 '0080 80.0 69.55023 -12.30339 0.0 0.001 0.0\n',
 '0083 83.0 69.58752 -12.30232 0.0 0.001 0.0\n',
 '0085 85.0 69.56567 -12.30147 0.0 0.001 0.0\n',
 '0111 111.0 69.59927 -12.29414 0.0 0.001 0.0\n',
 '0114 114.0 69.52129 -12.2893 0.0 0.001 0.0\n',
 '0119 119.0 69.5651 -12.28924 0.0 0.001 0.0\n',
 '0125 125.0 69.53808 -12.28883 0.0 0.001 0.0\n',
 '0126 126.0 69.54177 -12.28782 0.0 0.001 0.0\n',
 '0128 128.0 69.60646 -12.28668 0.369864207858 8.03355766875e-05 0.0\n',
 '0164 164.0 69.52007 -12.24671 0.581369862213 0.000216496440347 2.0\n',
 '0182 182.0 69.53533 -12.25025 0.0 0.001 0.0\n',
 '0185 185.0 69.52459 -12.24

In [21]:
# repr is if we have special characters in the file as $ that can means some special things, it is taken into account
# with repr
f = open('data.txt', 'r')
for line in f.readlines():
    print(repr(line))

'# Name ID RA DEC z z_err zQF \n'
'0011 11.0 69.60398 -12.33483 0.14502699731 5.39539923983e-05 0.0 \n'
'0038 38.0 69.5969 -12.32047 0.502938602945 0.000222303791245 1.0 \n'
'0042 42.0 69.57136 -12.31795 0.0 0.001 0.0 \n'
'0055 55.0 69.59832 -12.31157 0.0 0.001 0.0 \n'
'0057 57.0 69.5978429 -12.311442 0.0 0.001 0.0 \n'
'0072 72.0 69.61111 -12.3037 0.0 0.001 0.0\n'
'0080 80.0 69.55023 -12.30339 0.0 0.001 0.0\n'
'0083 83.0 69.58752 -12.30232 0.0 0.001 0.0\n'
'0085 85.0 69.56567 -12.30147 0.0 0.001 0.0\n'
'0111 111.0 69.59927 -12.29414 0.0 0.001 0.0\n'
'0114 114.0 69.52129 -12.2893 0.0 0.001 0.0\n'
'0119 119.0 69.5651 -12.28924 0.0 0.001 0.0\n'
'0125 125.0 69.53808 -12.28883 0.0 0.001 0.0\n'
'0126 126.0 69.54177 -12.28782 0.0 0.001 0.0\n'
'0128 128.0 69.60646 -12.28668 0.369864207858 8.03355766875e-05 0.0\n'
'0164 164.0 69.52007 -12.24671 0.581369862213 0.000216496440347 2.0\n'
'0182 182.0 69.53533 -12.25025 0.0 0.001 0.0\n'
'0185 185.0 69.52459 -12.24947 0.585115787002 0.000104162060008 

 Once a line is read, it is possible to apply string methods, as on normal string:    
- Remove `\n`: `line.strip()`
- Split the string into list of strings: `line.split()`
- Replace a specific character by another: `line.replace(',', '.')`  replaces each comma by a dot.
- Access a specific element of a splitted list and convert it to float: `float(line.split()[2])`

#### II.5.3: Saving an array into a file: 

To write a file, you basically follow the same procedure: 
``` python
with open('myfile.txt', 'w') as f:
    f.writelines(mylist_of_lines)   # mylist_of_lines contains the lines you want to write. Ensure that they end with `\n`

# you can also use:
    f.write(mylist_of_lines[0]+mylist_of_lines[1]+ ... + mylist_of_lines_[n])  # you can use list comprenhesion as argument
```

**Exercise:**

Read the file `data.txt` and display the some columns you care about for that file using:
- the file object
- Try to do the same using `numpy.loadtxt()`        
- Try to build a numpy array with the data in data.txt as read using `f = open('data.txt')`. 
- Modify 1 column of the file (replace it with 0) and write the results in `data_new.txt`


#### II.5.4 Formatting Strings

It often happens that you do not need to save all the decimals of a number, or would like to see it in scientific notation. There are [multiple ways to do it](https://docs.python.org/3/tutorial/inputoutput.html). One could spend (boring) hours describing all possible ways to format strings. The main 2 options are described below. You may look at https://pyformat.info/ to skim through various examples of formatting. The options described below explains you the basics and points you to relevant documentation.  A slightly more expanded version of this section can be consulted in [Modules_in_python_numpy_adv.ipynb](Modules_in_python_numpy_adv.ipynb)

- **Option 1**: `printf-style` (simple (old style) but not universal) 

You can use the `%` operator to specify the formatting of the variable you want to show at the screen or save in a file. The variable does not appear explicitly in the string but after it in a tuple, preceded by the `%`. Within the string, the `%` operator will be followed by a format string such as `%f` for a float or `%e` for scientific notation. The sequence `'%.2f'%variable` basically tells that the `%` operator converts the `variable` into a float with 2 digits after the dot. This is generalized to a sequence of variable, by defining the tuple object that contains all the variables to be formatted (but you need to specify the format you want for those, the association between the format and the variable being done easily as you have put your variable into a tuple-object). 

Example:
``` python
print('%i is the square of %i' %(4.000, 2))
    Out: 4 is the square of 2
```
Here are some commonly used formatting characters:
- `%s`: String (or any object with a string representation, like numbers)
- `%d` or `%i`: Integers
- `%.<number_of_digits>f`: Floating point numbers with fixed number of digits to the right of the dot. 
- `%.<number_of_digits>e`: scientific notation with fixed number of digits to the right of the dot.
You may find more about string formatting in [python 2 documentation](https://docs.python.org/2/library/stdtypes.html#string-formatting).  


In [ ]:
# Experiment with the above examples 

In [1]:
# What do we do if we want to go from scientific notations to normal notations for example
data[10, 2]

NameError: name 'data' is not defined

In [29]:
# If we only want 2 digits
print('my variable = %.2f'%data[10, 2])

my variable = 69.52


In [32]:
# .4i is if we always want integers with 4 digits for example
print('my variables = %.4i, %.2f'%(data[10,0], data[10,2]))

my variables = 0114, 69.52


In [34]:
# With this method, it always be returned as a string
'%.2e'%data[10,2]

'6.95e+01'

- **Option 2**: `str.format()` method    (NOT REALLY SEEN IN COURSE)

This is a much more flexible and general method described in details at https://docs.python.org/3/library/string.html#formatstrings. Format strings contain `replacement fields` surrounded by curly braces `{}`. This looks like: 

``` python
'val1 = {0:format_spec} and val2 = {1:format_spec}'.format(val1, val2)
```

Anything that is *not* contained in braces is considered literal text, which is *copied unchanged to the output*. See [here](https://docs.python.org/3/library/string.html#format-specification-mini-language) and [here](https://pyformat.info/) for more details and EXAMPLES. 

Example:
``` python
print('{0:.0f} is the square of {1:n}'.format(4.000, 2))
    Out: 4 is the square of 2
```
If you wich a float representation with 2 decimals: `{0:.2f}`
You can also use the positional argument to revert the output:
``` python
print('{1:.0f} is the square of {0:n}'.format(2, 4.000))
    Out: 4 is the square of 2
```

**Note**: 
- About `conversion field`: There are 3 possible conversions flags: `!s` which calls [str()](https://docs.python.org/3/library/stdtypes.html#str) on the value, `!r` which calls [repr()](https://docs.python.org/3/library/functions.html#repr) and `!a` which calls [ascii()](https://docs.python.org/3/library/functions.html#ascii).
- About `format_spec`: 
See https://docs.python.org/3/library/string.html#format-specification-mini-language

In [37]:
# Experiment with the above examples
# 0 and 1 are here the index of the value we give in the paranthesis of the .format(), see below if we reverse
print('{0:.0f} is the square of {1:n}'.format(4.000, 2))

4 is the square of 2


In [38]:
print('{1:.0f} is the square of {0:n}'.format(4.000, 2))

2 is the square of 4


In [ ]:
# Create three float variables a, b, c and give them some value (e.g. a=2.3, b=3, c=-5). 
# Print the sentence: `a=2.00, b=3 and c=-5.00e+00` using the formating format described above.

In [ ]:
# Create a 1-D array of 5 floats and print their value with 2 digits floats. TIP: use list comprehension

**Note**: There is another very useful way in python to save "full objects" and access and use them later using all their characteristics. This can be done by importing the `pickle` [module](https://docs.python.org/2/library/pickle.html), or even better (faster) [cPickle]( http://docs.python.org/library/pickle.html#module-cPickle). When you want to write a pickle into a file, simply open your file (`pkl_file = open()`), use `pickle.dump(obj, pkl_file, protocol=-1)`, and close your file (`pkl_file.close()`). To read an object saved in a pickle file, you can follow the same procedure but use `	obj = pickle.load(pkl_file)` instead of `pickle.dump()`. The `pandas` module also allows you to read/write pickle objects: see `pandas.read_pickle()` and `pandas.to_pickle()`

### II.6 Other useful numpy function:  <a class="anchor" id="II.6"></a>

There are many useful functions for manipulating arrays, finding elements, compare arrays, ... that are predefined. Do not hesitate to have a look at the `numpy` help. I list below a few "must-know". You may consult [Modules_in_python_numpy_adv.ipynb](Modules_in_python_numpy_adv.ipynb) for a compilation of "may-know" (i.e. 75\% chance that one of them will save your day in a project).

- `np.sort(a)`: Returns sorted copy of an array along a specific axis (default = last axis)
- `np.searchsorted(a, v)`: Find indices where elements should be inserted to maintain order.
- `np.concatenate(a1, a2, ...)`: Join a sequence of arrays along an existing axis.
- `np.hstack(tup)` / `np.vstack(tup)`: Stack arrays in sequence horizontally/vertically (column-/row- wise).
- `np.where(condition, [x, y])`: Return elements chosen from `x` or `y` depending on `condition`.


### II.7 Summary:   <a class="anchor" id="II.7"></a>

What do you need to know to get started?

- Know how to create arrays : `np.array`, `np.arange`, `np.ones`, `np.zeros`, `np.linspace()`.

- Know the shape of the array with `array.shape`, then use *slicing* to obtain different views of the array: `array[start:end:step]` (and variations around that syntax). Adjust the shape of the array using reshape or flatten it with ravel.

- Obtain a subset of the elements of an array and/or modify their values with masks (`a[a < 0] = 0`).

- Know miscellaneous operations on arrays, such as finding the mean or max (`ufunct`: `array.max()`, `array.mean()`). Have the reflex to search in the documentation (online docs, `help()`, `np.lookfor()`) when you do not remember exact syntax of a function !!

- Master the *indexing* with arrays of integers, as well as *broadcasting*. Know more NumPy functions to handle various array operations.

- Be able to read/write data into a file, and format numbers at screen (or when writing them into files): `open()`, `close()`, `np.savetxt()/np.loadtxt()`, use of `%` operator and the `.format()` string method. 


## II.8 References and supplementary material: <a class="anchor" id="VI"></a>

- Excellent video introducing numpy (and that inspired part of the numpy section of this notebook) by J. Vandeplas: https://www.youtube.com/watch?v=EEUXKG97YRw

- Numpy quick-start: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

- About string formatting: https://docs.python.org/3/tutorial/inputoutput.html